In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
import pandas as pd
pd.__version__

'1.3.1'

In [3]:
import os
os.chdir('Desktop')

In [49]:
df = pd.read_csv('hw.csv')
df['Make'].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

In [32]:
2170 + 2157 + 1668

5995

(5995, 16)

In [41]:
a = df2['Engine HP']
a.isna().sum()

51

In [6]:
df1 = df[df['Make'] == 'BMW']
df1

Make       Model  Year             Engine Fuel Type  Engine HP  \
0      BMW  1 Series M  2011  premium unleaded (required)      335.0   
1      BMW    1 Series  2011  premium unleaded (required)      300.0   
2      BMW    1 Series  2011  premium unleaded (required)      300.0   
3      BMW    1 Series  2011  premium unleaded (required)      230.0   
4      BMW    1 Series  2011  premium unleaded (required)      230.0   
...    ...         ...   ...                          ...        ...   
11901  BMW          Z4  2016  premium unleaded (required)      240.0   
11902  BMW          Z4  2016  premium unleaded (required)      335.0   
11903  BMW          Z8  2001  premium unleaded (required)      394.0   
11904  BMW          Z8  2002  premium unleaded (required)      394.0   
11905  BMW          Z8  2003  premium unleaded (required)      394.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL  rear wheel drive              2.0   
1                   6.0            MANUAL  rear wheel drive              2.0   
2                   6.0            MANUAL  rear wheel drive              2.0   
3                   6.0            MANUAL  rear wheel drive              2.0   
4                   6.0            MANUAL  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11903               8.0            MANUAL  rear wheel drive              2.0   
11904               8.0            MANUAL  rear wheel drive              2.0   
11905               8.0            MANUAL  rear wheel drive              2.0   

                             Market Category Vehicle Size Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                         Luxury,Performance      Compact   Convertible   
2                    Luxury,High-Performance      Compact         Coupe   
3                         Luxury,Performance      Compact         Coupe   
4                                     Luxury      Compact   Convertible   
...                                      ...          ...           ...   
11901                     Luxury,Performance      Compact   Convertible   
11902                Luxury,High-Performance      Compact   Convertible   
11903         Exotic,Luxury,High-Performance      Compact   Convertible   
11904         Exotic,Luxury,High-Performance      Compact   Convertible   
11905         Exotic,Luxury,High-Performance      Compact   Convertible   

       highway MPG  city mpg  Popularity    MSRP  
0               26        19        3916   46135  
1               28        19        3916   40650  
2               28        20        3916   36350  
3               28        18        3916   29450  
4               28        18        3916   34500  
...            ...       ...         ...     ...  
11901           34        22        3916   49700  
11902           24        17        3916   66350  
11903           19        12        3916  128000  
11904           19        12        3916  130000  
11905           19        12        3916  131500  

[334 rows x 16 columns]

In [45]:
df2 = df[df['Year']>2014]

In [46]:
np.mean(a['Engine HP'])

272.98771870794076

In [47]:
a = df2.fillna(df2.mean())
np.mean(a['Engine HP'])

C:\Users\asus\AppData\Local\Temp/ipykernel_2504/2905384082.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  a = df2.fillna(df2.mean())


272.98771870794076

In [42]:
r = np.mean(df1.MSRP)
print(round(r))

45667


In [58]:
df3 = df[df['Make'] == 'Rolls-Royce']
df3 = df3[['Engine HP', 'Engine Cylinders', 'highway MPG']]
df3 = df3.drop_duplicates()

In [59]:
x = df3
x

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [62]:
y = x.T
y

2921   3505   5275   5279   7443   7553   11448
Engine HP         325.0  563.0  563.0  563.0  322.0  453.0  624.0
Engine Cylinders    8.0   12.0   12.0   12.0   12.0   12.0   12.0
highway MPG        15.0   19.0   21.0   20.0   15.0   19.0   21.0

In [81]:
z = np.dot(y, x)
z

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [82]:
inverse = np.linalg.inv(z)
inverse

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [83]:
s = sum(inverse)
s

array([-0.00097147,  0.01792124,  0.01526256])

In [99]:
l = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [102]:
l = l.reshape(7,1)
l.shape

(7, 1)

In [103]:
a = np.dot(inverse, y)

In [104]:
a

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [105]:
ans = np.dot(a, l)
ans

array([[ 0.19989598],
       [31.02612262],
       [31.65378877]])